export const projects = [
  {
    id: 'ccs-payment-web',
    title: 'CCS Payment Transaction System — Web',
    type: 'Capstone · Full-stack',
    description: 'A secure payment and transaction platform for the College of Computing Studies, with student accounts, payment records, QR workflows, dashboards, and administrative reports.',
    image: '/assets/projects/work0.webp',
    technologies: ['Node.js', 'MySQL', 'Bootstrap', 'REST API'],
    live: 'https://finalccspayment.onrender.com/',
  },
  {
    id: 'ccs-payment-mobile',
    title: 'CCS Payment Transaction System — Mobile',
    type: 'Mobile application',
    description: 'The companion React Native application for students, connected to the CCS payment backend for account access, transaction monitoring, and mobile-first services.',
    image: '/assets/projects/work2.webp',
    technologies: ['React Native', 'Expo', 'Node.js API', 'Mobile UX'],
    live: 'https://expo.dev/accounts/ameeffy/projects/ccspayment/builds/7d83470e-f38d-4676-9b12-cb1e644f6da0',
  },
  {
    id: 'dental-clinic',
    title: 'WMSU Dental Clinic Appointment System',
    type: 'Healthcare scheduling',
    description: 'A Django appointment platform built for the WMSU Dental Clinic, covering schedules, patient requests, service records, and clinic administration.',
    image: '/assets/projects/work3.webp',
    technologies: ['Django', 'Python', 'Chart.js', 'Bootstrap'],
    live: '/livedemoexpired',
  },
  {
    id: 'goodys-food',
    title: "Goody’s Food E-Commerce Platform",
    type: 'E-commerce',
    description: 'An online food ordering and store-management experience featuring menus, customer orders, product administration, and operational reporting.',
    image: '/assets/projects/work4.webp',
    technologies: ['PHP', 'MySQL', 'JavaScript', 'Bootstrap'],
    live: '/livedemoexpired',
  },
  {
    id: 'lost-and-found',
    title: 'WMSU Lost & Found Application',
    type: 'Community platform',
    description: 'A campus platform for reporting, searching, tracking, and resolving lost-and-found cases through organized listings and user accounts.',
    image: '/assets/projects/work5.webp',
    technologies: ['Django', 'SQLite', 'Bootstrap', 'Authentication'],
    live: '/livedemoexpired',
  },
  {
    id: 'grandd-map',
    title: 'GrandD Campus Map Navigation',
    type: 'Navigation & prediction',
    description: 'An interactive campus navigation system with mapped facilities, route guidance, step estimates, and distance prediction.',
    image: '/assets/projects/work6.webp',
    technologies: ['Django', 'Machine Learning', 'JavaScript', 'CSS'],
    live: '/livedemoexpired',
  },
  {
    id: 'todo-list',
    title: 'DoItNow Todo List',
    type: 'Productivity app',
    description: 'A focused task-management application for creating, prioritizing, updating, completing, and organizing daily work.',
    image: '/assets/projects/sidework1.webp',
    technologies: ['React', 'JavaScript', 'CSS', 'Local State'],
    live: 'https://ameeff-elisan-todolist.netlify.app/',
  },
  {
    id: 'pokeguide',
    title: 'PokeGuide',
    type: 'API-powered guide',
    description: 'A responsive Pokémon discovery experience with searchable character cards, type information, favorites, and polished visual interactions.',
    image: '/assets/projects/sidework2.webp',
    technologies: ['JavaScript', 'REST API', 'CSS3', 'Responsive UI'],
    live: 'https://pokeguide-elisan-adjarail.netlify.app/',
  },
  {
    id: 'trac-appointment',
    title: 'TRAC Office of the President Appointment System',
    type: 'Institutional operations',
    description: 'A digital appointment and scheduling platform for the Office of the President, designed around visitor requests, approvals, time conflicts, and office workflows.',
    image: '/assets/projects/work7.webp',
    technologies: ['Node.js', 'MySQL', 'Tailwind CSS', 'Email OTP'],
    live: '/livedemoexpired',
  },
  {
    id: 'trac-certification',
    title: 'TRAC Certification & Event Management System',
    type: 'Enterprise web system',
    description: 'A role-based platform for appointments, events, QR-verifiable certificates, evaluations, email notifications, analytics, audit logs, and document workflows.',
    image: '/assets/projects/trac-certification.svg',
    technologies: ['Node.js', 'MySQL', 'QR Verification', 'Analytics'],
    live: '/livedemoexpired',
  },
];

export const simplilearnCertificates = [
  ['Introduction to Cyber Security', 'https://simpli-web.app.link/e/yb5k8UJG6Sb'],
  ['Introduction to Data Science', 'https://simpli-web.app.link/e/esEcIYcG6Sb'],
  ['Introduction to Machine Learning with R', 'https://simpli-web.app.link/e/eYslMJoG6Sb'],
  ['Getting Started with Full Stack Java Development', 'https://simpli-web.app.link/e/P1Li3oGG6Sb'],
  ['Python for Beginners', 'https://simpli-web.app.link/e/eqwHXMEG6Sb'],
  ['Introduction to SQL', 'https://simpli-web.app.link/e/gOEsxCHG6Sb'],
  ['ChatGPT for Cybersecurity', 'https://simpli-web.app.link/e/197CeR4F6Sb'],
  ['Introduction to Front End Development', 'https://simpli-web.app.link/e/Gl39gVNG6Sb'],
  ['Introduction to Artificial Intelligence', 'https://simpli-web.app.link/e/IEeytQPG6Sb'],
  ['Introduction to Cloud Security', 'https://simpli-web.app.link/e/yTFDNgRG6Sb'],
  ['Deep Learning for Beginners', 'https://simpli-web.app.link/e/n6pJSBWG6Sb'],
  ['Python Libraries for Data Science', 'https://simpli-web.app.link/e/TVWVxUXG6Sb'],
  ['ReactJS for Beginners', 'https://simpli-web.app.link/e/Odgly9YG6Sb'],
  ['Azure Fundamentals', 'https://simpli-web.app.link/e/Z1Yxwl0G6Sb'],
  ['Artificial Intelligence: Beginner’s Guide', 'https://simpli-web.app.link/e/TDQpLT1G6Sb'],
  ['Introduction to Data Visualization', 'https://simpli-web.app.link/e/ODTxWY4G6Sb'],
  ['Getting Started with Machine Learning Algorithms', 'https://simpli-web.app.link/e/mfCFlz6G6Sb'],
  ['Getting Started with Node.js', 'https://simpli-web.app.link/e/RzWv3O7G6Sb'],
  ['Basics of Data Structures and Algorithms', 'https://simpli-web.app.link/e/Revtqh9G6Sb'],
  ['Advanced Python', 'https://simpli-web.app.link/e/MmZRJUaH6Sb'],
  ['Introduction to Data Analytics', 'https://simpli-web.app.link/e/ZNtTP7bH6Sb'],
  ['Data Analytics Projects', 'https://simpli-web.app.link/e/1IynBsdH6Sb'],
  ['Introduction to Cryptography for Beginners', 'https://simpli-web.app.link/e/0fMBRGhH6Sb'],
  ['Introduction to Google Cloud Platform', 'https://simpli-web.app.link/e/NWqbWYiH6Sb'],
  ['Introduction to Data Mining', 'https://simpli-web.app.link/e/AfQQD6jH6Sb'],
  ['Ethical Hacking 101', 'https://simpli-web.app.link/e/4wMhW59L6Sb'],
  ['AI & ML Projects', 'https://simpli-web.app.link/e/PsH0anjh7Sb'],
  ['Introduction to Neural Networks', 'https://simpli-web.app.link/e/t4sc79mh7Sb'],
].map(([title, link], index) => ({ id: index + 1, title, link }));

export const learningPrograms = [
  {
    id: 1,
    title: '2025 PASUC Midterm Convention and General Assembly — Forging the Future: Empowering SUCs Through Innovation, Sustainability, and Excellence',
    shortTitle: '2025 PASUC Midterm Convention',
    from: '09 Jul 2025', to: '11 Jul 2025', hours: 24, ldType: 'Managerial', eventType: 'Convention',
    sponsor: 'Philippine Association of State Universities and Colleges',
    images: ['/assets/certificates/pasuc-midterm.webp'],
  },
  {
    id: 2,
    title: 'Presidents’ Summit 2025 — Quality Assurance and Accreditation: New Framework, New Directions',
    shortTitle: 'Presidents’ Summit 2025',
    from: '14 Aug 2025', to: '15 Aug 2025', hours: 16, ldType: 'Managerial', eventType: 'Summit',
    sponsor: 'Accrediting Agency of Chartered Colleges and Universities in the Philippines',
    images: ['/assets/certificates/presidents-summit.webp'],
  },
  {
    id: 3,
    title: 'MASTS Games 2025 Sports, Culture and the Arts Competition — Head Coach, TRAC MLBB E-Sports',
    shortTitle: 'MASTS Games 2025',
    from: '26 Oct 2025', to: '30 Oct 2025', hours: 40, ldType: 'Sports & Leadership', eventType: 'Sports Competition',
    sponsor: 'Mindanao Association of State Tertiary Schools, Inc.',
    images: ['/assets/certificates/masts-games.webp'],
  },
  {
    id: 4,
    title: 'Supervisory Development Course Track I — Supervisory and Leadership Management',
    shortTitle: 'Supervisory Development Course Track I',
    from: '18 Nov 2025', to: '22 Nov 2025', hours: 40, ldType: 'Supervisory', eventType: 'Training',
    sponsor: 'Civil Service Commission for BARMM',
    images: ['/assets/certificates/supervisory-development.webp'],
  },
  {
    id: 5,
    title: 'From Knowledge to Action: Championing the Role of State Universities and Colleges for Accelerated Climate Action',
    shortTitle: 'Climate Action Forum',
    from: '09 Dec 2025', to: '09 Dec 2025', hours: 8, ldType: 'Technical', eventType: 'Forum',
    sponsor: 'Climate Change Commission — Philippines',
    images: ['/assets/certificates/climate-action-forum.webp'],
  },
  {
    id: 6,
    title: 'Gender and Development Seminar — WE for Gender Equality and Inclusion: Building Trust, Uniting TRAC, and Achieving Progress',
    shortTitle: 'Gender and Development Seminar',
    from: '14 Dec 2025', to: '14 Dec 2025', hours: 8, ldType: 'Technical', eventType: 'Seminar',
    sponsor: 'Tawi-Tawi Regional Agricultural College', images: [],
  },
  {
    id: 7,
    title: 'TRAC Team Building Activity — WE for Gender Equality and Inclusion: Building Trust, Uniting TRAC, and Achieving Progress',
    shortTitle: 'TRAC Team Building Activity',
    from: '15 Dec 2025', to: '15 Dec 2025', hours: 8, ldType: 'Technical', eventType: 'Team Building',
    sponsor: 'Tawi-Tawi Regional Agricultural College',
    images: ['/assets/certificates/trac-team-building.webp'],
  },
  {
    id: 8,
    title: 'Sustaining Traditions, Securing Futures: Community Knowledge in Food Security, Disaster Response, Climate Change Adaptation, and Women Empowerment',
    shortTitle: 'Sustaining Traditions, Securing Futures',
    from: '21 Jan 2026', to: '23 Jan 2026', hours: 24, ldType: 'Technical', eventType: 'Conference',
    sponsor: 'University of California, Los Angeles & Western Mindanao State University',
    images: ['/assets/certificates/sustaining-traditions.webp'],
  },
  {
    id: 9,
    title: 'Capacity Building for State Universities and Colleges',
    shortTitle: 'Capacity Building for SUCs',
    from: '05 Feb 2026', to: '05 Feb 2026', hours: 8, ldType: 'Technical', eventType: 'Capacity Building',
    sponsor: 'Department of Budget and Management — Regional Office IX',
    images: ['/assets/certificates/dbm-capacity-building.webp'],
  },
  {
    id: 10,
    title: 'Fiscal Year 2027 Regional Budget Forum',
    shortTitle: 'FY 2027 Regional Budget Forum',
    from: '06 Feb 2026', to: '06 Feb 2026', hours: 8, ldType: 'Technical', eventType: 'Forum',
    sponsor: 'Department of Budget and Management — Regional Office IX',
    images: ['/assets/certificates/dbm-budget-forum.webp'],
  },
  {
    id: 11,
    title: 'Coordination Meeting and Reorientation on the Salient Provisions of UAQTE Programs under Republic Act No. 10931',
    shortTitle: 'UAQTE Coordination Meeting',
    from: '23 Feb 2026', to: '23 Feb 2026', hours: 8, ldType: 'Technical', eventType: 'Coordination Meeting',
    sponsor: 'UniFAST & Commission on Higher Education',
    images: ['/assets/certificates/uaqte-reorientation.webp'],
  },
  {
    id: 12,
    title: 'CHED RAISE 2026 — Raising AI Education, Empowering Society',
    shortTitle: 'CHED RAISE 2026',
    from: '25 Feb 2026', to: '27 Feb 2026', hours: 24, ldType: 'Technical', eventType: 'Conference',
    sponsor: 'Commission on Higher Education, Northern Iloilo State University & West Visayas State University',
    images: ['/assets/certificates/ched-raise-appearance.webp', '/assets/certificates/ched-raise-participation.webp'],
  },
  {
    id: 13,
    title: 'Higher Education Summit 2026 — Co-Creating the ACHIEVE Agenda with Multistakeholders',
    shortTitle: 'Higher Education Summit 2026',
    from: '10 Mar 2026', to: '11 Mar 2026', hours: 16, ldType: 'Managerial', eventType: 'Summit',
    sponsor: 'Commission on Higher Education, Department of Science and Technology & Bulacan State University',
    images: ['/assets/certificates/higher-ed-summit-appearance.webp', '/assets/certificates/higher-ed-summit-participation-a.webp', '/assets/certificates/higher-ed-summit-participation-b.webp'],
  },
  {
    id: 14,
    title: 'Training on Research Ethics and Organizational Development — PHILARM Elite 2026',
    shortTitle: 'Research Ethics & Organizational Development',
    from: '12 Mar 2026', to: '14 Mar 2026', hours: 24, ldType: 'Technical', eventType: 'Training',
    sponsor: 'Philippine Association of Research Managers, Inc.',
    images: ['/assets/certificates/philarm-elite.webp'],
  },
  {
    id: 15,
    title: 'Strategic Directions 2026: Workshop and Strategic Planning for Institutional Excellence',
    shortTitle: 'Strategic Directions 2026',
    from: '24 Mar 2026', to: '25 Mar 2026', hours: 16, ldType: 'Technical', eventType: 'Workshop',
    sponsor: 'Tawi-Tawi Regional Agricultural College',
    images: ['/assets/certificates/strategic-directions.webp'],
  },
  {
    id: 16,
    title: '2026 PSITE National Convention — PSITE 2.0: Augmenting Education, Connecting Community, and Thriving with AI',
    shortTitle: '2026 PSITE National Convention',
    from: '26 Mar 2026', to: '28 Mar 2026', hours: 24, ldType: 'Technical', eventType: 'Convention',
    sponsor: 'Philippine Society of Information Technology Educators, Inc.',
    images: ['/assets/certificates/psite-appearance.webp', '/assets/certificates/psite-participation.webp'],
  },
];

export const memberships = [
  {
    name: 'Council of Deans and Educators in Computing, Inc. — Region IX',
    short: 'CODEC Region IX',
    status: 'Active membership',
    validity: 'Valid until December 2026',
    image: '/assets/memberships/codec-membership.webp',
    description: 'Professional membership supporting collaboration, standards, and development among computing educators and academic leaders.',
  },
  {
    name: 'Philippine Association of Research Managers, Inc.',
    short: 'PHILARM',
    status: 'Individual membership',
    validity: 'Registered March 2026',
    image: '/assets/memberships/philarm-membership.webp',
    description: 'Professional association focused on research management, ethics, institutional research capacity, and organizational development.',
  },
];

export const skills = [
  { group: 'Development', items: ['JavaScript', 'React', 'React Native', 'Node.js', 'PHP', 'Python', 'Django'] },
  { group: 'Data & Systems', items: ['MySQL', 'SQLite', 'REST APIs', 'Database Design', 'Data Handling', 'QR Workflows'] },
  { group: 'Analytics & Productivity', items: ['Microsoft Excel', 'Power BI', 'Data Visualization', 'Word', 'PowerPoint', 'Technical Documentation'] },
  { group: 'Professional', items: ['Project Coordination', 'Research Management', 'Leadership', 'Instruction', 'Continuous Learning'] },
];

export const education = [
  { school: 'Bulacan State University', degree: 'Master of Science in Information Technology', period: '2025 — Present', note: 'Graduate studies focused on advanced computing, research, and technology management.', logo: '/assets/education/bulsu.webp' },
  { school: 'Western Mindanao State University', degree: 'Bachelor of Science in Information Technology', period: '2021 — 2025', note: 'Mobile and web development, databases, systems analysis, and capstone development.', logo: '/assets/education/wmsu.webp' },
  { school: 'Filipino-Turkish Tolerance School', degree: 'Junior & Senior High School — HUMSS', period: '2015 — 2021', note: 'Graduated with high honors and athletic recognition.', logo: '/assets/education/turkish.webp' },
  { school: 'Bongao Adventist Elementary School', degree: 'Elementary Education', period: '2012 — 2015', note: 'Academic excellence and mathematics recognition.', logo: '/assets/education/adventist.webp' },
  { school: 'Notre Dame of Bongao', degree: 'Kindergarten & Elementary Education', period: '2008 — 2012', note: 'Early academic foundation and class distinction.', logo: '/assets/education/notre-dame.webp' },
];

export const blogPosts = [
  ['Industry Immersion Begins', 'A first look at organizations, infrastructure, and professional technology environments during our educational tour.', '/assets/blog/day-1.webp'],
  ['Systems, Operations & Collaboration', 'Learning how teams coordinate systems, information, and operational decisions in real institutions.', '/assets/blog/day-2.webp'],
  ['Technology Behind Public Services', 'Observations on the digital tools and structured processes that support day-to-day public services.', '/assets/blog/day-3.webp'],
  ['Museums, History & Digital Storytelling', 'A reflective day connecting culture, history, visual communication, and technology-assisted storytelling.', '/assets/blog/day-4.webp'],
  ['LRT Operations and Infrastructure', 'Inside the planning, monitoring, and coordination that keep a major urban transport system moving.', '/assets/blog/day-5.webp'],
  ['Baguio Adventure', 'A full day across La Trinidad, Bell Church, PMA, The Mansion, Mines View, and Burnham Park.', '/assets/blog/day-6.webp'],
  ['EducTour Finale', 'A quiet, memorable conclusion to the tour and a final appreciation of the places and experiences shared.', '/assets/blog/day-7.webp'],
  ['Paws & Places', 'A lighthearted collection of the cats encountered across Metro Manila and Baguio during the journey.', '/assets/blog/day-8.webp'],
  ['Joyful Return', 'Family time, city walks, and meaningful moments after the educational tour.', '/assets/blog/day-9.webp'],
].map(([title, excerpt, image], index) => ({ id: index + 1, title, excerpt, image, label: `Journal ${String(index + 1).padStart(2, '0')}` }));
